apiVersion: apps/v1
kind: Deployment

metadata:
  name: base-name
  namespace: base-namespace

spec:
  template:
    spec:
      containers:
        - name: base-image
          image: base-image:base-version

          env:
            - name: DB_USER
              value: ${vault:apps/demo-webserver@DB_USER}
            - name: DB_PASSWORD
              value: ${vault:apps/demo-webserver@DB_PASSWORD}