kind: Service
apiVersion: v1

metadata:
  name: base-name
  namespace: base-namespace

spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: "base-app"

  type: ClusterIP