apiVersion: v1
kind: List
items:
  - apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - ldap:
          attributes:
            email:
            - mail
            id:
            - dn
            name:
            - cn
            preferredUsername:
            - corpAliasLocal
          bindDN: "CN=Admin,CN=Users,DC=example,DC=com"
          bindPassword:
            name: ldap
          insecure: false
          url: ldap://ldap.example.com/o=Acme?cn?sub?(enabled=true)
        mappingMethod: claim
        name: ldap
        type: LDAP
