apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role-openshift-oauth
rules:
- apiGroups:
    - "config.openshift.io"
  resources:
    - oauths
  verbs:
    - get
    - list
    - create
    - delete
    - update
    - patch
    #- watch
    #- '*'
