# Role to allow creating routes
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-openshift-routes
rules:
- apiGroups:
    - "route.openshift.io"
  resources:
    - routes
  verbs:
    - get
    - list
    - create
    - delete
    - update
    - patch
    #- watch
    #- '*'
