# Role binding example to set Role role-openshift-routes to a 
# argocd-argocd-application-controller ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-openshift-routes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-openshift-routes
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: demo01
