# This is an example of creating a RoleBinding to allow a serviceaccount 
# from another project to create resources in this project
#
# Example:
#    oc project demo03
#    oc apply -f example-role-binding-admin.yaml
#
# In this example the service account argocd-argocd-application-controller 
# of the namespace demo-webserver gets admin access in this project, in
# this case demo03

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: demo01
